### ISSUE TITLE
The `limit` field of `fetc_aggregate` is gone

### ISSUE THREAD

**Issue by hoh** [aleph-im/aleph-sdk-python#114]
Previous versions of the SDK allowed to specify the `limit` argument of fetch_aggregate, while this now gone and breaks compatibility. Is this argument still relevant ?

https://github.com/aleph-im/aleph-sdk-python/blob/3d1452f7eeb996429ba6238a8675c5eb22c9890b/src/aleph/sdk/client/http.py#L83-L92

**Comment by MHHukiewitz** [comment]
It has completely no use anymore
