### ISSUE TITLE
Replace `setup.cfg` with `pyproject.toml`

### ISSUE THREAD

**Issue by hoh** [aleph-im/aleph-sdk-python#72]
`pyproject.toml` is the new standard format for specifying package metadata in Python.

The `aleph-vm` project switched to it recently, see [aleph-vm/pyproject.toml](https://github.com/aleph-im/aleph-vm/blob/main/pyproject.toml).

Documentation is available on:

https://packaging.python.org/en/latest/tutorials/packaging-projects/
https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/

On `aleph-vm`, we found the use of the `hatch` command from the first documentation very handy to run tests and reformat the code.

**Comment by MHHukiewitz** [comment]
Hey @ofek, thank you for reaching out! Right now, no one's actively working on it.

We highly encourage people to contribute to the project with PRs, I'd love to review it!

**Comment by MHHukiewitz** [comment]
We successfully converted to Hatch in #111 :+1:

**Comment by ofek** [comment]
Nice job!
